# Generated by Django 5.2.6 on 2025-11-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(db_column='AddressID', primary_key=True, serialize=False)),
                ('postcode', models.CharField(db_column='PostCode', max_length=12)),
            ],
            options={
                'db_table': 'Address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefinedListDetail',
            fields=[
                ('defined_list_detail_id', models.IntegerField(db_column='DefinedListDetailID', primary_key=True, serialize=False)),
                ('dld_name', models.CharField(db_column='Name', max_length=50)),
                ('unique_id', models.CharField(db_column='UniqueID', max_length=50)),
            ],
            options={
                'db_table': 'DefinedListDetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetProposer',
            fields=[
                ('pet_proposer_id', models.IntegerField(db_column='PetProposerID', primary_key=True, serialize=False)),
                ('address_id', models.IntegerField(db_column='AddressID')),
                ('title_dldid', models.IntegerField(db_column='TitleDLDID')),
                ('ph_dob', models.DateField(db_column='DateOfBirth')),
            ],
            options={
                'db_table': 'PetProposer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetRisk',
            fields=[
                ('risk_id', models.IntegerField(db_column='RiskID', primary_key=True, serialize=False)),
                ('pet_proposer_id', models.IntegerField(db_column='PetProposerID')),
                ('pet_cover_level_dldid', models.IntegerField(db_column='PetCoverLevelDLDID')),
            ],
            options={
                'db_table': 'PetRisk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetRiskPet',
            fields=[
                ('pet_risk_pet_id', models.IntegerField(db_column='PetRiskPetID', primary_key=True, serialize=False)),
                ('pet_type_dldid', models.IntegerField(db_column='PetTypeDLDID')),
                ('pet_sub_type_dldid', models.IntegerField(db_column='PetSubTypeDLDID')),
                ('breed_dldid', models.IntegerField(db_column='BreedDLDID')),
                ('size_dldid', models.IntegerField(db_column='SizeDLDID')),
                ('gender_dldid', models.IntegerField(db_column='GenderDLDID')),
                ('risk_id', models.IntegerField(db_column='RiskID')),
                ('cost_of_pet', models.IntegerField(db_column='CostofPet')),
                ('pet_dob', models.DateField(db_column='DateofBirth')),
                ('pet_name', models.CharField(db_column='Name', max_length=50)),
                ('prn', models.IntegerField(db_column='PRN')),
                ('neutered', models.IntegerField(db_column='HasBeenNeutered')),
                ('chipped', models.IntegerField(db_column='HasBeenChipped')),
                ('pre_existing', models.IntegerField(db_column='HasExistingMedicalConditions')),
                ('vaccinations', models.IntegerField(db_column='HasUpToDateVaccinations')),
                ('aggressive', models.IntegerField(db_column='HasAttacked')),
                ('proposer_owns_pet', models.IntegerField(db_column='ProposerOwnsPet')),
            ],
            options={
                'db_table': 'PetRiskPet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyHistory',
            fields=[
                ('policy_history_id', models.IntegerField(db_column='PolicyHistoryID', primary_key=True, serialize=False)),
                ('policy_master_id', models.IntegerField(db_column='PolicyMasterID')),
                ('risk_id', models.IntegerField(db_column='RiskID')),
                ('adustment_number', models.IntegerField(db_column='AdjustmentNumber')),
                ('creation_date', models.DateTimeField(db_column='CreationDate')),
                ('effective_date', models.DateTimeField(db_column='EffectiveDate')),
                ('scheme_quote_result_id', models.IntegerField(db_column='SchemeQuoteResultID')),
                ('transaction_type_id', models.IntegerField(db_column='TransactionTypeID')),
                ('gwp', models.FloatField(db_column='CalculatedNetPremiumExclIPT')),
            ],
            options={
                'db_table': 'PolicyHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyMaster',
            fields=[
                ('policy_master_id', models.IntegerField(db_column='PolicyMasterID', primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(db_column='CustomerID')),
                ('product_id', models.IntegerField(db_column='ProductID')),
                ('policy_status_id', models.IntegerField(db_column='PolicyStatusID')),
                ('policy_number', models.CharField(db_column='PolicyNumber', max_length=50)),
                ('live_risk_id', models.IntegerField(db_column='LiveRiskID')),
                ('renewal_date', models.DateTimeField(db_column='RenewalDate')),
                ('scheme_id', models.IntegerField(db_column='SchemeID')),
                ('cancellation_effective_date', models.DateTimeField(db_column='CancellationEffectiveDate')),
            ],
            options={
                'db_table': 'PolicyMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('risk_id', models.IntegerField(db_column='RiskID', primary_key=True, serialize=False)),
                ('copay', models.IntegerField(db_column='CoinsuranceRuleID')),
            ],
            options={
                'db_table': 'Risk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchemeQuoteResultComment',
            fields=[
                ('scheme_quote_result_comment_id', models.IntegerField(db_column='SchemeQuoteResultCommentID', primary_key=True, serialize=False)),
                ('scheme_quote_result_id', models.IntegerField(db_column='SchemeQuoteResultID')),
                ('comment_text', models.CharField(db_column='CommentText', max_length=50)),
                ('order', models.IntegerField(db_column='Order')),
                ('premium_total', models.FloatField(db_column='PremiumTotal')),
                ('loading_value', models.FloatField(db_column='LoadingValue')),
            ],
            options={
                'db_table': 'SchemeQuoteResultComment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('transaction_type_id', models.IntegerField(db_column='TransactionTypeID', primary_key=True, serialize=False)),
                ('transaction_name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'TransactionType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=10)),
                ('scheme', models.CharField(max_length=50)),
                ('factor', models.CharField(max_length=50)),
                ('option', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.FloatField()),
                ('limit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('pet_type', 'scheme', 'factor', 'option')},
            },
        ),
    ]
