# Generated by Django 5.2.6 on 2025-10-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyHistory',
            fields=[
                ('policyhistoryid', models.IntegerField(db_column='PolicyHistoryID', primary_key=True, serialize=False)),
                ('policymasterid', models.IntegerField(db_column='PolicyMasterID')),
                ('adustmentnumber', models.IntegerField(db_column='AdjustmentNumber')),
                ('creationdate', models.DateTimeField(db_column='CreationDate')),
                ('effectivedate', models.DateTimeField(db_column='EffectiveDate')),
                ('schemequoteresultid', models.IntegerField(db_column='SchemeQuoteResultID')),
                ('gwp', models.FloatField(db_column='CalculatedNetPremiumExclIPT')),
            ],
            options={
                'db_table': 'PolicyHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyMaster',
            fields=[
                ('policymasterid', models.IntegerField(db_column='PolicyMasterID', primary_key=True, serialize=False)),
                ('customerid', models.IntegerField(db_column='CustomerID')),
                ('productid', models.IntegerField(db_column='ProductID')),
                ('policystatusid', models.IntegerField(db_column='PolicyStatusID')),
                ('policynumber', models.CharField(db_column='PolicyNumber', max_length=50)),
                ('liveriskid', models.IntegerField(db_column='LiveRiskID')),
                ('renewaldate', models.DateTimeField(db_column='RenewalDate')),
                ('schemeid', models.IntegerField(db_column='SchemeID')),
                ('cancellationeffectivedate', models.DateTimeField(db_column='CancellationEffectiveDate')),
            ],
            options={
                'db_table': 'PolicyMaster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('riskid', models.IntegerField(db_column='RiskID', primary_key=True, serialize=False)),
                ('copay', models.IntegerField(db_column='CoinsuranceRuleID')),
            ],
            options={
                'db_table': 'Risk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('transactiontypeid', models.IntegerField(db_column='TransactionTypeID', primary_key=True, serialize=False)),
                ('trans_name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'TransactionType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PetRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=10)),
                ('scheme', models.CharField(max_length=50)),
                ('factor', models.CharField(max_length=50)),
                ('option', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.FloatField()),
                ('limit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('pet_type', 'scheme', 'factor', 'option')},
            },
        ),
    ]
