from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    # path('policy_list/', views.policy_list, name='policy_list'),
    # path('gwp-summaries/', views.gwp_summaries, name='gwp-summary'),
    path('quote_data/', views.quote_data, name='quote_data'),
    path('rates/', views.rates, name='rates'),
    path('rates/prem_calc/', views.prem_calc, name='prem_calc'),
    path("rates/get_pet_rates/", views.get_pet_rates, name="get_pet_rates"),
    path('rates/base_rates/', views.base_rates, name='base_rates'),
    path('rates/postcode/', views.postcode, name='postcode'),
    path('rates/breed/', views.breed, name='breed'),
    path('rates/multipet/', views.multipet, name='multipet'),
    path('rates/copay/', views.copay, name='copay'),
    path('rates/chipped/', views.chipped, name='chipped'),
    path('rates/ph_age/', views.ph_age, name='ph_age'),
    path('rates/pet_age/', views.pet_age, name='pet_age'),
    path('rates/pet_price/', views.pet_price, name='pet_price'),
    path('rates/neutered/', views.neutered, name='neutered'),
    path('rates/pet_age_gender/', views.pet_age_gender, name='pet_age_gender'),
    path('rates/vaccinations/', views.vaccinations, name='vaccinations'),
    path('rates/pre_existing/', views.pre_existing, name='pre_existing'),
    path('rates/aggressive/', views.aggressive, name='aggressive'),
    path('rates/is_pet_yours/', views.is_pet_yours, name='is_pet_yours'),
    path('rates/uk_resident/', views.uk_resident, name='uk_resident'),
    path('rates/kept_at_address/', views.kept_at_address, name='kept_at_address'),
    path('rates/trade_business/', views.trade_business, name='trade_business'),
    path('rates/re_rated_policies/', views.re_rated_policies, name='re_rated_policies'),
    path('rates/test/', views.test, name='test'),
]